### ISSUE TITLE
Using gzip on graphql-java-spring-webmvc

### ISSUE THREAD

**Issue by jmdsg** [graphql-java/graphql-java-spring#20]
Hi, is there any way to gzip the response when the request headers contains a `Accept-Encoding: gzip`.

Thanks in advance.

**Comment by jmdsg** [comment]
Just found the answer.

Need to add this to my `application.properties` or `application.yml`:

```yaml
server:
    compression:
        enabled: true
        mime-types: application/json
        min-response-size: 10240 # only compress responses over 10KiB
```
